routes/web.php
<?php

use App\Http\Controllers\DeliveryController;
use App\Http\Controllers\DonationCenterController;
use App\Http\Controllers\DonationController;
use App\Http\Controllers\FoodController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\MissingController;
use App\Http\Controllers\NeedCategoryController;
use App\Http\Controllers\NeedController;
use App\Http\Controllers\NeedNameController;
use App\Http\Controllers\NotifaibleController;
use App\Http\Controllers\RequestController;
use App\Http\Controllers\ShelterController;
use App\Http\Controllers\SupportController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontController::class, 'index']);
Route::get('/food-support', [FrontController::class, 'food_support']);
Route::get('/stuck-in-rubble-report', [FrontController::class, 'stuck_in_rubble']);
Route::get('/shelter-support', [FrontController::class, 'shelter_support']);
Route::get('/medical-support', [FrontController::class, 'medical_support']);
Route::get('/f/teams', [FrontController::class, 'teams']);
Route::get('/f/donations', [FrontController::class, 'donations']);
Route::get('/f/shelters', [FrontController::class, 'shelters']);
Route::post('/requests', [RequestController::class, 'store'])->name('requests.store');

Auth::routes();

Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');

Route::group(['middleware' => 'auth'], function(){
    Route::resource('/missings', MissingController::class, ['names' => 'missings']);
    Route::resource('/shelters', ShelterController::class, ['names' => 'shelters']);
    Route::resource('/foods', FoodController::class, ['names' => 'foods']);
    Route::resource('/deliveries', DeliveryController::class, ['names' => 'deliveries']);
    Route::resource('/supports', SupportController::class, ['names' => 'supports']);
    Route::resource('/requests', RequestController::class, ['names' => 'requests'])->except('store');
    Route::resource('/teams', TeamController::class, ['names' => 'teams']);
    Route::resource('/donations', DonationController::class, ['names' => 'donations']);
    Route::resource('/notifaibles', NotifaibleController::class, ['names' => 'notifaibles']);
    Route::resource('/need_categories', NeedCategoryController::class, ['names' => 'need_categories']);
    Route::resource('/donation_centers', DonationCenterController::class, ['names' => 'donation_centers']);
    Route::resource('/needs', NeedController::class, ['names' => 'needs']);
    Route::resource('/need_names', NeedNameController::class, ['names' => 'need_names']);
});

app/Models/Support.php
<?php

namespace App\Models;

use App\Models\Scopes\FilterScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Support extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'state_id',
        'added_by',
        'notes',
        'responsible',
        'status'
    ];

    protected static function booted()
    {
        static::addGlobalScope(new FilterScope);
        static::creating(function (Support $model) {
            $model->added_by = auth('sanctum')->id();
        });
    }

    public function state(){
        return $this->belongsTo(State::class);
    }
}

app/Http/Controllers/SupportController.php
<?php

namespace App\Http\Controllers;

use App\Exports\SupportsExport;
use App\Http\Requests\SupportRequest;
use App\Models\State;
use App\Models\Support;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class SupportController extends Controller
{
    public function index(Request $request){
        if($request->submit == 'export_excel'){
            return $this->excel();
        }else{
            return view('supports.index', [
                'supports' => Support::with('state')->paginate(15),
                'states' => State::orderBy('name', 'asc')->get()
            ]);
        }
    }

    public function excel(){
        return Excel::download(new SupportsExport, 'supports.xlsx');
    }

    public function create(){
        return view('supports.create', [
            'states' => State::orderBy('name', 'asc')->get()
        ]);
    }

    public function store(SupportRequest $request){
        $data = $request->validated();

        Support::create($data);

        return redirect(route('supports.index'))->with('success', 'تمت إضافة طلب المتطوعين بنجاح');
    }

    public function show(Support $support){
        return view('supports.show', compact('support'));
    }

    public function edit(Support $support){
        return view('supports.edit', [
            'support' => $support,
            'states' => State::orderBy('name', 'asc')->get()
        ]);
    }

    public function update(SupportRequest $request, Support $support){
        $data = $request->validated();

        $support->update($data);

        return redirect(route('supports.show', ['support' => $support->id]))->with('success', 'تم تعديل بيانات طلب المتطوعين بنجاح');
    }

    public function destroy(Support $support){
        $support->delete();
        return redirect(route('supports.index'))->with('success', 'تم حذف طلب المتطوعين بنجاح');
    }
}

resources/views/supports/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card mb-4">
                <div class="card-header"><strong>إضافة طلب متطوعين</strong></div>
                <div class="card-body">
                    <form method="POST" action="{{ route('supports.store') }}">
                        @csrf
                        <div class="mb-3 row">
                            <div class="col-md-12">
                                <label class="form-label" for="state">المحافظة <b class="text-danger">*</b></label>
                                <select class="form-control" id="state" name="state_id">
                                    <option value="0">--</option>
                                    @foreach ($states as $s)
                                        <option value="{{ $s->id }}">{{ $s->name }}</option>
                                    @endforeach
                                </select>
                                @error('state_id')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <div class="col-md-6">
                                <label class="form-label" for="name">الاسم <b class="text-danger">*</b></label>
                                <input class="form-control" name="name" id="name" type="text" value="{{ old('name') }}">
                                @error('name')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="col-md-6">
                                <label class="form-label" for="responsible">المسؤول عن المتابعة <b class="text-danger">*</b></label>
                                <input class="form-control" name="responsible" id="responsible" type="text" value="{{ old('responsible') }}">
                                @error('responsible')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <div class="col-md-6">
                                <label class="form-label" for="status">الحالة <b class="text-danger">*</b></label>
                                <select class="form-control" id="status" name="status">
                                    <option value="1">قيد البحث</option>
                                    <option value="2">مكتمل</option>
                                </select>
                                @error('status')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3">
                            <div class="col-md-12">
                                <label class="form-label" for="notes">ملاحظات</label>
                                <textarea class="form-control" name="notes" id="notes" cols="30" rows="5">{{ old('notes') }}</textarea>
                                @error('notes')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3">
                            <button class="btn btn-success" type="submit">إضافة</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/supports/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card mb-4">
                <div class="card-header"><strong>تعديل بيانات طلب متطوعين</strong></div>
                <div class="card-body">
                    <form method="POST" action="{{ route('supports.update', ['support' => $support->id]) }}">
                        @csrf
                        @method('PUT')
                        <div class="mb-3 row">
                            <div class="col-md-12">
                                <label class="form-label" for="state">المحافظة <b class="text-danger">*</b></label>
                                <select class="form-control" id="state" name="state_id">
                                    <option value="0">--</option>
                                    @foreach ($states as $s)
                                        <option value="{{ $s->id }}" {{ ($s->id == $support->state_id) ? 'selected' : '' }}>{{ $s->name }}</option>
                                    @endforeach
                                </select>
                                @error('state_id')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <div class="col-md-6">
                                <label class="form-label" for="name">الاسم <b class="text-danger">*</b></label>
                                <input class="form-control" name="name" id="name" type="text" value="{{ $support->name }}">
                                @error('name')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="col-md-6">
                                <label class="form-label" for="responsible">المسؤول عن المتابعة <b class="text-danger">*</b></label>
                                <input class="form-control" name="responsible" id="responsible" type="text" value="{{ $support->responsible }}">
                                @error('responsible')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <div class="col-md-6">
                                <label class="form-label" for="status">الحالة <b class="text-danger">*</b></label>
                                <select class="form-control" id="status" name="status">
                                    <option value="1" {{ ($support->status == 1) ? 'selected' : '' }}>قيد البحث</option>
                                    <option value="2" {{ ($support->status == 2) ? 'selected' : '' }}>مكتمل</option>
                                </select>
                                @error('status')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3">
                            <div class="col-md-12">
                                <label class="form-label" for="notes">ملاحظات</label>
                                <textarea class="form-control" name="notes" id="notes" cols="30" rows="5">{{ $support->notes }}</textarea>
                                @error('notes')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3">
                            <button class="btn btn-primary" type="submit">حفظ</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/supports/index.blade.php
@extends('layouts.app')

@section('content')
<!-- /.row-->
<div class="row">
    <div class="col-md-12">
        <div class="card mb-4">
            <div class="card-header">إدارة بيانات طلبات المتطوعين</div>
            <div class="card-body">
                <a href="{{ route('supports.create') }}" class="btn btn-sm btn-success">إضافة طلب متطوعين</a>
                <br><hr>
                <form method="GET" action="{{ route('supports.index') }}" class="row">
                    <div class="col-lg-4 col-md-12">
                        من:
                        <input type="date" name="from" class="form-control form-control-sm" value="{{ request()->get('from') }}">
                    </div>
                    <div class="col-lg-4 col-md-12">
                        إلى:
                        <input type="date" name="to" class="form-control form-control-sm" value="{{ request()->get('to') }}">
                    </div>
                    <div class="col-lg-4 col-md-12">
                        المحافظة:
                        <select class="form-control form-control-sm" name="state">
                            <option value="0" {{ request()->get('state') == 0 ? 'selected' : ''}}>الكل</option>
                            @foreach ($states as $s)
                                <option value="{{ $s->id }}" {{ request()->get('state') == $s->id ? 'selected' : ''}}>{{ $s->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="col-lg-4 col-md-12">
                        الاسم:
                        <input type="text" name="subject" class="form-control form-control-sm" value="{{ request()->get('name') }}">
                    </div>
                    <div class="col-lg-3 col-md-12">
                        ترتيب حسب:
                        <select class="form-control form-control-sm" name="sort">
                            <option value="0">الأقدم</option>
                            <option value="1">الأحدث</option>
                        </select>
                    </div>
                    <div class="col-lg-3 col-md-12">
                        الحالة:
                        <select class="form-control form-control-sm" name="status">
                            <option value="0" {{ request()->get('status') == 0 ? 'selected' : ''}}>الكل</option>
                            <option value="1" {{ request()->get('status') == 1 ? 'selected' : ''}}>قيد البحث</option>
                            <option value="2" {{ request()->get('status') == 2 ? 'selected' : ''}}>ممتلئ</option>
                        </select>
                    </div>
                    <div class="col-lg-1 col-md-12">
                        بحث:
                        <div>
                            <button type="submit" class="btn btn-sm btn-primary" name="submit" value="search">بحث</button>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-12">
                        تصدير:
                        <div>
                            <button class="btn btn-sm btn-success" type="submit" name="submit" value="export_excel">تصدير إلى Excel</button>
                        </div>
                    </div>
                </form>
                <div class="table-responsive mt-3">
                    <table class="table border mb-0">
                        <thead class="table-light fw-semibold">
                            <tr class="align-middle">
                                <th class="text-center">
                                    الرقم التسلسلي
                                </th>
                                <th>الاسم</th>
                                <th>ملاحظات</th>
                                <th>الفريق المسؤول</th>
                                <th>الحالة</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($supports as $s)
                                <tr class="align-middle">
                                    <td class="text-center">
                                        {{ $s->id }}
                                    </td>
                                    <td>
                                        {{ $s->name }}
                                    </td>
                                    <td>
                                        {{ $s->notes }}
                                    </td>
                                    <td>
                                        {{ $s->responsible }}
                                    </td>
                                    <td>
                                        @if ($s->status == 1)
                                            <span class="badge bg-danger text-light">قيد البحث</span>
                                        @else
                                            <span class="badge bg-success text-light">مكتمل</span>
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        <a href="{{ route('supports.show', ['support' => $s->id]) }}"
                                            class="btn btn-sm btn-secondary">
                                            <svg class="icon">
                                                <use
                                                    xlink:href="{{ asset('vendors/@coreui/icons/svg/free.svg#cil-list') }}">
                                                </use>
                                            </svg>
                                        </a>
                                        <a href="{{ route('supports.edit', ['support' => $s->id]) }}"
                                            class="btn btn-sm btn-primary">
                                            <svg class="icon">
                                                <use
                                                    xlink:href="{{ asset('vendors/@coreui/icons/svg/free.svg#cil-pencil') }}">
                                                </use>
                                            </svg>
                                        </a>
                                        <form class="d-inline"
                                            action="{{ route('supports.destroy', ['support' => $s->id]) }}"
                                            method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-sm btn-danger">
                                                <svg class="icon">
                                                    <use
                                                        xlink:href="{{ asset('vendors/@coreui/icons/svg/free.svg#cil-trash') }}">
                                                    </use>
                                                </svg>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="10" class="text-center">لا يوجد بيانات</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
                <hr>
                <div class="mt-3">
                    @if ($supports->count() > 0)
                        {{ $supports->withQueryString()->links() }}
                    @endif
                </div>
            </div>
        </div>
    </div>
    <!-- /.col-->
</div>
@endsection

resources/views/supports/show.blade.php
@extends('layouts.app')

@section('content')
    <!-- /.row-->
    <div class="row justify-content-center">
        <div class="col-md-12 col-lg-6">
            <div class="card mb-4">
                <div class="card-header"> معلومات طلب متطوعين #{{ $support->id }}</div>
                <div class="card-body text-right">
                    <table class="table border">
                        <tr>
                            <td>الرقم التسلسلي: </td>
                            <td><b>{{ $support->id }}</b></td>
                        </tr>
                        <tr>
                            <td>الاسم: </td>
                            <td><b>{{ $support->name }}</b></td>
                        </tr>
                        <tr>
                            <td>المسؤول عن المتابعة: </td>
                            <td><b>{{ $support->responsible }}</b></td>
                        </tr>
                        <tr>
                            <td>الحالة: </td>
                            <td>
                                @if ($support->status == 1)
                                    <span class="badge bg-danger text-light">قيد البحث</span>
                                @else
                                    <span class="badge bg-success text-light">مكتمل</span>
                                @endif
                            </td>
                        </tr>
                        <tr>
                            <td>ملاحظات: </td>
                            <td><b>{{ $support->notes }}</b></td>
                        </tr>
                    </table>

                    <!--QR Code-->
                </div>
            </div>
        </div>
        <!-- /.col-->
    </div>
@endsection