routes/web.php
<?php

use App\Http\Controllers\DeliveryController;
use App\Http\Controllers\DonationCenterController;
use App\Http\Controllers\DonationController;
use App\Http\Controllers\FoodController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\MissingController;
use App\Http\Controllers\NeedCategoryController;
use App\Http\Controllers\NeedController;
use App\Http\Controllers\NeedNameController;
use App\Http\Controllers\NotifaibleController;
use App\Http\Controllers\RequestController;
use App\Http\Controllers\ShelterController;
use App\Http\Controllers\SupportController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontController::class, 'index']);
Route::get('/food-support', [FrontController::class, 'food_support']);
Route::get('/stuck-in-rubble-report', [FrontController::class, 'stuck_in_rubble']);
Route::get('/shelter-support', [FrontController::class, 'shelter_support']);
Route::get('/medical-support', [FrontController::class, 'medical_support']);
Route::get('/f/teams', [FrontController::class, 'teams']);
Route::get('/f/donations', [FrontController::class, 'donations']);
Route::get('/f/shelters', [FrontController::class, 'shelters']);
Route::post('/requests', [RequestController::class, 'store'])->name('requests.store');

Auth::routes();

Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');

Route::group(['middleware' => 'auth'], function(){
    Route::resource('/missings', MissingController::class, ['names' => 'missings']);
    Route::resource('/shelters', ShelterController::class, ['names' => 'shelters']);
    Route::resource('/foods', FoodController::class, ['names' => 'foods']);
    Route::resource('/deliveries', DeliveryController::class, ['names' => 'deliveries']);
    Route::resource('/supports', SupportController::class, ['names' => 'supports']);
    Route::resource('/requests', RequestController::class, ['names' => 'requests'])->except('store');
    Route::resource('/teams', TeamController::class, ['names' => 'teams']);
    Route::resource('/donations', DonationController::class, ['names' => 'donations']);
    Route::resource('/notifaibles', NotifaibleController::class, ['names' => 'notifaibles']);
    Route::resource('/need_categories', NeedCategoryController::class, ['names' => 'need_categories']);
    Route::resource('/donation_centers', DonationCenterController::class, ['names' => 'donation_centers']);
    Route::resource('/needs', NeedController::class, ['names' => 'needs']);
    Route::resource('/need_names', NeedNameController::class, ['names' => 'need_names']);
});

app/Models/NeedName.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class NeedName extends Model
{
    use HasFactory;

    protected $fillable = [
        'name'
    ];
}

app/Http/Controllers/NeedNameController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\NeedNameRequest;
use App\Models\NeedName;
use Illuminate\Http\Request;

class NeedNameController extends Controller
{
    public function index(){
        return view('need_names.index', [
            'need_names' => NeedName::paginate(15),
        ]);
    }

    public function create(){
        return view('need_names.create');
    }

    public function store(NeedNameRequest $request){
        $data = $request->validated();

        NeedName::create($data);

        return redirect(route('need_names.index'))->with('success', 'تمت إضافة اسم المادة بنجاح');
    }

    public function show(NeedName $need_name){
        return view('need_names.show', compact('need_name'));
    }

    public function edit(NeedName $need_name){
        return view('need_names.edit', [
            'need_name' => $need_name,
        ]);
    }

    public function update(NeedNameRequest $request, NeedName $need_name){
        $data = $request->validated();

        $need_name->update($data);

        return redirect(route('need_names.show', ['need_name' => $need_name->id]))->with('success', 'تم تعديل اسم المادة بنجاح');
    }

    public function destroy(NeedName $need_name){
        $need_name->delete();
        return redirect(route('need_names.index'))->with('success', 'تم حذف اسم المادة بنجاح');
    }
}

resources/views/need_names/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-6">
            <div class="card mb-4">
                <div class="card-header"><strong>إضافة اسم مادة</strong></div>
                <div class="card-body">
                    <form method="POST" action="{{ route('need_names.store') }}">
                        @csrf
                        <div class="mb-3 row">
                            <div class="col-md-12">
                                <label class="form-label" for="name">الاسم <b class="text-danger">*</b></label>
                                <input class="form-control" name="name" id="name" type="text" value="{{ old('name') }}">
                                @error('name')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3">
                            <button class="btn btn-success" type="submit">إضافة</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/need_names/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-6">
            <div class="card mb-4">
                <div class="card-header"><strong>تعديل اسم المادة</strong></div>
                <div class="card-body">
                    <form method="POST" action="{{ route('need_names.update', ['need_name' => $need_name->id]) }}">
                        @csrf
                        @method('PUT')
                        <div class="mb-3 row">
                            <div class="col-md-12">
                                <label class="form-label" for="name">الاسم <b class="text-danger">*</b></label>
                                <input class="form-control" name="name" id="name" type="text" value="{{ $need_name->name }}">
                                @error('name')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3">
                            <button class="btn btn-primary" type="submit">حفظ</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/need_names/index.blade.php
@extends('layouts.app')

@section('content')
<!-- /.row-->
<div class="row">
    <div class="col-md-12">
        <div class="card mb-4">
            <div class="card-header">إدارة قائمة أسماء المواد</div>
            <div class="card-body">
                <a href="{{ route('need_names.create') }}" class="btn btn-sm btn-success">إضافة اسم مادة</a>
                <br><hr>
                <div class="table-responsive mt-3">
                    <table class="table border mb-0">
                        <thead class="table-light fw-semibold">
                            <tr class="align-middle">
                                <th class="text-center">
                                    الرقم التسلسلي
                                </th>
                                <th>الاسم</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($need_names as $nn)
                                <tr class="align-middle">
                                    <td class="text-center">
                                        {{ $nn->id }}
                                    </td>
                                    <td>
                                        {{ $nn->name }}
                                    </td>
                                    <td class="text-center">
                                        <a href="{{ route('need_names.show', ['need_name' => $nn->id]) }}"
                                            class="btn btn-sm btn-secondary">
                                            <svg class="icon">
                                                <use
                                                    xlink:href="{{ asset('vendors/@coreui/icons/svg/free.svg#cil-list') }}">
                                                </use>
                                            </svg>
                                        </a>
                                        <a href="{{ route('need_names.edit', ['need_name' => $nn->id]) }}"
                                            class="btn btn-sm btn-primary">
                                            <svg class="icon">
                                                <use
                                                    xlink:href="{{ asset('vendors/@coreui/icons/svg/free.svg#cil-pencil') }}">
                                                </use>
                                            </svg>
                                        </a>
                                        <form class="d-inline"
                                            action="{{ route('need_names.destroy', ['need_name' => $nn->id]) }}"
                                            method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-sm btn-danger">
                                                <svg class="icon">
                                                    <use
                                                        xlink:href="{{ asset('vendors/@coreui/icons/svg/free.svg#cil-trash') }}">
                                                    </use>
                                                </svg>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="10" class="text-center">لا يوجد بيانات</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
                <hr>
                <div class="mt-3">
                    @if ($need_names->count() > 0)
                        {{ $need_names->withQueryString()->links() }}
                    @endif
                </div>
            </div>
        </div>
    </div>
    <!-- /.col-->
</div>
@endsection

resources/views/need_names/show.blade.php
@extends('layouts.app')

@section('content')
    <!-- /.row-->
    <div class="row justify-content-center">
        <div class="col-md-12 col-lg-6">
            <div class="card mb-4">
                <div class="card-header"> معلومات اسم المادة #{{ $need_name->id }}</div>
                <div class="card-body text-right">
                    <table class="table border">
                        <tr>
                            <td>الرقم التسلسلي: </td>
                            <td><b>{{ $need_name->id }}</b></td>
                        </tr>
                        <tr>
                            <td>الاسم: </td>
                            <td><b>{{ $need_name->name }}</b></td>
                        </tr>
                    </table>

                    <!--QR Code-->
                </div>
            </div>
        </div>
        <!-- /.col-->
    </div>
@endsection